Fix KW issue
projectceladon/MemTrack pull request #1
Opened 2019-07-03 06:47 UTC by hongcheng-xie

Tracked-On: OAM-83690
Signed-off-by: Hongcheng Xie <hongcheng.xie@intel.com>

2019-07-03 06:49 UTC, qshi5 approved these changes

2019-07-03 08:49 UTC, sysopenci reviewed
Autobuild started from pull-request-changes on this PR.

Cactus automatically verified this PR.

For more information, see: /absp/builders/celadon-autobuild/builds/1068

2019-07-09 03:03 UTC, arvinwax commented
Verfy +1, running command:
adb shell dumpsys meminfo
Catch memtrack:

        939K: android.hardware.memtrack@1.0-service (pid 2777)

2019-07-09 06:03 UTC, swaroopbalan approved these changes

2019-07-12 07:50 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/649

2019-07-16 02:52 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/654

2019-07-16 03:09 UTC, btian1 approved these changes

2019-07-16 03:09 UTC, btian1 approved these changes

2019-07-16 03:11 UTC, btian1 requested changes
please change title to: fix debug and trace memtrack code compatibility issue.

2019-07-16 06:11 UTC, btian1 approved these changes

2019-07-16 08:43 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/656

Done by "Luo, LilianX" <lilianx.luo@intel.com>

2019-07-16 09:20 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-premerge/builds/311

2019-07-17 01:21 UTC, zhy1030 approved these changes

2019-07-17 01:32 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-premerge/builds/318

2019-07-17 07:29 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-premerge/builds/319

2019-07-17 07:33 UTC, qshi5 approved these changes

2019-07-17 08:43 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: Trigger blocking tests Triggered: EAT(apl_nuc:r2_cel_apl - userdebug), EAT(kbl_nuc:r2_cel_kbl - userdebug), EAT(kbl_nuc:r2_celadon - userdebug)

More details, logs, and binaries: /absp/builders/celadon-premerge/builds/320

2019-07-17 08:53 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: Trigger blocking tests cancelled

More details, logs, and binaries: /absp/builders/celadon-premerge/builds/323

2019-07-17 14:47 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: Trigger blocking tests Triggered: EAT(apl_nuc:r2_cel_apl - userdebug), EAT(kbl_nuc:r2_cel_kbl - userdebug), EAT(kbl_nuc:r2_celadon - userdebug)

More details, logs, and binaries: /absp/builders/celadon-premerge/builds/322

2019-07-18 01:49 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: Trigger blocking tests cancelled

More details, logs, and binaries: /absp/builders/celadon-premerge/builds/330

2019-07-18 15:23 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/679

Done by "Luo, LilianX" <lilianx.luo@intel.com>

2019-07-19 02:20 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/340

Done by "Luo, LilianX" <lilianx.luo@intel.com>

2019-07-19 03:47 UTC, merged

2019-07-19 03:47 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Luo, LilianX" <lilianx.luo@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/991